artifact_location: /home/vladislav/Рабочий стол/44/mse1h2026-markup-ml-main/markup_ml/runs/mlflow/0
creation_time: 1774294951642
experiment_id: '0'
last_update_time: 1774294951642
lifecycle_stage: active
name: Default
workspace: default
