artifact_location: /home/vladislav/Рабочий стол/gg/mse/mse-yaml-and-front_merged/mse/runs/mlflow/0
creation_time: 1774428208920
experiment_id: '0'
last_update_time: 1774428208920
lifecycle_stage: active
name: Default
workspace: default
