artifact_uri: /home/vladislav/Рабочий стол/gg/mse/mse-yaml-and-front_merged/mse/runs/mlflow/998325131461347536/4ed5df3bfc3148d2bf0a46f6627420be/artifacts
end_time: 1774429365809
entry_point_name: ''
experiment_id: '998325131461347536'
lifecycle_stage: active
run_id: 4ed5df3bfc3148d2bf0a46f6627420be
run_name: trial_003
source_name: ''
source_type: 4
source_version: ''
start_time: 1774429323291
status: 3
tags: []
user_id: vladislav
