artifact_uri: /home/vladislav/Рабочий стол/gg/mse/mse-yaml-and-front_merged/mse/runs/mlflow/998325131461347536/91c0ceb1446d4c63b61c801a05afeafa/artifacts
end_time: 1774429246116
entry_point_name: ''
experiment_id: '998325131461347536'
lifecycle_stage: active
run_id: 91c0ceb1446d4c63b61c801a05afeafa
run_name: trial_001
source_name: ''
source_type: 4
source_version: ''
start_time: 1774429204931
status: 3
tags: []
user_id: vladislav
