artifact_location: /home/vladislav/Рабочий стол/gg/mse/mse-yaml-and-front_merged/mse/runs/mlflow/998325131461347536
creation_time: 1774428208933
experiment_id: '998325131461347536'
last_update_time: 1774428208933
lifecycle_stage: active
name: runs/detect/automl
workspace: default
