artifact_uri: /home/vladislav/Рабочий стол/44/mse1h2026-markup-ml-main/markup_ml/runs/mlflow/598737000304558487/bc58d2b080ea4cc59c7de2ba626ca3ab/artifacts
end_time: 1774377925632
entry_point_name: ''
experiment_id: '598737000304558487'
lifecycle_stage: active
run_id: bc58d2b080ea4cc59c7de2ba626ca3ab
run_name: trial_000
source_name: ''
source_type: 4
source_version: ''
start_time: 1774377876016
status: 3
tags: []
user_id: vladislav
