artifact_uri: /home/vladislav/Рабочий стол/44/mse1h2026-markup-ml-main/markup_ml/runs/mlflow/598737000304558487/9b5c9f9ab129472a9d0eef246df9dc8b/artifacts
end_time: 1774368080004
entry_point_name: ''
experiment_id: '598737000304558487'
lifecycle_stage: active
run_id: 9b5c9f9ab129472a9d0eef246df9dc8b
run_name: trial_000
source_name: ''
source_type: 4
source_version: ''
start_time: 1774368062152
status: 3
tags: []
user_id: vladislav
