artifact_location: /home/vladislav/Рабочий стол/44/mse1h2026-markup-ml-main/markup_ml/runs/mlflow/598737000304558487
creation_time: 1774294951665
experiment_id: '598737000304558487'
last_update_time: 1774294951665
lifecycle_stage: active
name: runs/detect/automl
workspace: default
