artifact_uri: /home/vladislav/Рабочий стол/44/mse1h2026-markup-ml-main/markup_ml/runs/mlflow/598737000304558487/5b23bc927062427c9dbc794fae7b5450/artifacts
end_time: null
entry_point_name: ''
experiment_id: '598737000304558487'
lifecycle_stage: active
run_id: 5b23bc927062427c9dbc794fae7b5450
run_name: trial_001
source_name: ''
source_type: 4
source_version: ''
start_time: 1774378376037
status: 1
tags: []
user_id: vladislav
